apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: api-checker
  newName: registry.digitalocean.com/k8s-arf-registry/api-checker
  newTag: 1f65efa42b7ff943c1f000b0960540f87e842f7f
