apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: api-checker
  newName: registry.digitalocean.com/k8s-arf-registry/api-checker
  newTag: e04ccb3d0fc010a248ca0e1004291fc847a0c542
