apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: api-checker
  newName: registry.digitalocean.com/k8s-arf-registry/api-checker
  newTag: 1bbbc6189f657c59114fd4df80a9dbcf70215b80
